### ISSUE TITLE
Implement MVP

### ISSUE THREAD

**Issue by srid** [srid/Taut#1]
## Goal
Load Slack export data into database.

## Tasks
- [x] Select a database library
- [x] Types for Slack export data
- [x] Parse and print
- [x] Insert into database

**Comment by srid** [comment]
Last month's reddit discussion of database libraries: https://www.reddit.com/r/haskell/comments/7tx0o4/haskell_3_sql/

**Comment by srid** [comment]
Beam stuff seams to be working. Next, need to clean up the types and import the current export.
