### ISSUE TITLE
Improve search query

### ISSUE THREAD

**Issue by srid** [srid/Taut#14]
- Searching for `foo bar` should search for both foo and bar, preferably preferring results containing both
- Searching for `"foo bar"` (in quotes) should perform an exact search
- Limit by date, eg: `after:<ts> foo` or `before:<ts>`. See [slack format](https://get.slack.help/hc/en-us/articles/202528808-Guide-to-search-in-Slack-#date-4).

## Tasks

- [ ] Add query parser
- [ ] Generate sql query from query type
- [ ] Blog post on query parser?
