### ISSUE TITLE
UI MVP

### ISSUE THREAD

**Issue by srid** [srid/Taut#2]
Create a basic UI to render the data (or a subset of it) from the database. Nothing fancy.

# Minimum feature

- Display messages on a day, with routes like: `/messages/2018/04/07`

# Tasks

- [x] Add message route
- [x] Add backend route, and query it from frontend
- [x] Parse `Day` when loading slack messages
- [x] Query from the backend route
- [x] Associate messages with their channel in Db
- [x] Render messages nicely in frontend
  - [x] Return `Users` along with `Messages` (need it to get actual username from userid) -- kind of hackish compared to `join` on server.

**Comment by srid** [comment]
Finished in recent commits.
